
services:
  wellbot:
    build:
      context: .
      args:
        PY_VER: "3.11"
    env_file:
      - backend/.env
    # Audio device mounting - Linux/Raspberry Pi only
    devices:
      - "/dev/snd:/dev/snd"
    group_add:
      - "audio"
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: ["python", "backend/main.py"]
